services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: transcendence_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-net

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
      target: dev
    container_name: transcendence_frontend
    volumes:
      - ./services/frontend:/app/services/frontend
      - ./packages/shared:/app/packages/shared
    ports:
      - "5173:5173"
    networks:
      - transcendence-net

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    container_name: transcendence_backend
    networks:
      - transcendence-net
    ports:
      - "3000:3000"
    volumes:
      - ./services/backend/data:/app/services/backend/data
      # - backend_data:/app

volumes:
  frontend_node_modules:
  backend_data:

networks:
  transcendence-net:
    driver: bridge